### ISSUE TITLE
successfully patched, but ray tracing is not enabled.

### ISSUE THREAD

**Issue by xxqt** [WakuWakuPadoru/WuWa_Simple_FPSUnlocker#22]
I've ran the problem and it managed to change the engine.ini and LocalStorange.db files. However when the game is launched everything remained the same.

**Comment by WakuWakuPadoru** [comment]
> I've ran the problem and it managed to change the engine.ini and LocalStorange.db files. However when the game is launched everything remained the same.

Restart the game once and see if it helps. Did you notice the frame rate dropping? Because the RT isn't always obvious.

**Comment by xxqt** [comment]
hey! I've alr restarted the game multiple times. the framerate seems to be the same. I have a 3080ti btw

**Comment by WakuWakuPadoru** [comment]
> hey! I've alr restarted the game multiple times. the framerate seems to be the same. I have a 3080ti btw

Thanks. Can you send me your Engine.ini, GameUserSettings.ini, and LocalStorage.db file? It's pretty weird.

**Comment by xxqt** [comment]
[LocalStorage.zip](https://github.com/user-attachments/files/18812136/LocalStorage.zip)

[Engine.-.2.txt](https://github.com/user-attachments/files/18812137/Engine.-.2.txt)

**Comment by xxqt** [comment]
[gameusersettings.txt](https://github.com/user-attachments/files/18812139/gameusersettings.txt)

**Comment by WakuWakuPadoru** [comment]
> [LocalStorage.zip](https://github.com/user-attachments/files/18812136/LocalStorage.zip)
> 
> [Engine.-.2.txt](https://github.com/user-attachments/files/18812137/Engine.-.2.txt)

Your Engine.ini file doesn't seem to be modified actually. If possible, can you do this:

1) DELETE Engine.ini and LocalStorage.DB file from WuWa.
2) Run the GAME at least once until you can move your character, then quit it.
3) Run the Unlocker.
4) Start the game up. (Make sure DX12)

**Comment by xxqt** [comment]
that strange, I gave you the wrong file for engine.ini

[engine.txt](https://github.com/user-attachments/files/18812176/engine.txt)

this was what the engine.ini file looked like originally after the initial "unlock"

**Comment by xxqt** [comment]
btw I followed the steps. same results

**Comment by WakuWakuPadoru** [comment]
> btw I followed the steps. same results

Typical questions then. 
What version of Windows are you using? Are you running the game in DX12 mode?

Just for sanity check, I uninstalled WuWa, redownloaded the installer from their website, installed ran the game once, ran the unlocker, then launched and restarted the game once. After that, shaders recompiled and RT was enabled.

**Comment by xxqt** [comment]
okay will do. I really appreciate the help btw

**Comment by WakuWakuPadoru** [comment]
> okay will do. I really appreciate the help btw

Updated to 0.83. Let me know if the latest version helps you :)

**Comment by WakuWakuPadoru** [comment]
> I am using windows 11.
> 
> I've uninstalled and reinstall WuWa. ran the unlocker again. checked the engine.ini and localstorage. 
> 
> "[/Script/Engine.RendererRTXSettings]...." got added to the end of engine.ini
> raytracing values got changed to 3,1,1, in local storage.
> 
> If you're at a wit's end, it fine. I'll wait til when wuwa added support for older gpus. thank for you time

Can you send the Local Storage and Engine file again? 

And your situation is so weird. By right, everything looks right so it should be working.

**Comment by xxqt** [comment]
[Engine.zip](https://github.com/user-attachments/files/18813421/Engine.zip)

[LocalStorage.zip](https://github.com/user-attachments/files/18813424/LocalStorage.zip)

**Comment by a4840639** [comment]
I also have this issue
Somebody on Reddit told me they managed to get it working by enabling low RT first but no luck on my side (I have regenerated both engine.ini and the sqlite DB many times)

**Comment by a4840639** [comment]
I am digging the the client log and it is the log also says it is enabled

`[2025.02.15-19.39.36:227][  0][GameThread]LogRendererCore: Ray tracing is enabled (dynamic) for the game. Reason: r.RayTracing=1 and r.RayTracing.EnableOnDemand=1.`

But it certainly isn't because I still have the same FPS as it was off and I do not see any RT reflection standing in front of a lake
Not sure if these lines of log are expected:
`[2025.02.15-19.39.35:809][  0][GameThread]LogConfig: Setting CVar [[r.RayTracing:1]]
[2025.02.15-19.39.35:809][  0][GameThread]LogConfig: Setting CVar [[r.RayTracing.Enable:0]]
[2025.02.15-19.39.35:809][  0][GameThread]LogConfig: Setting CVar [[r.RayTracing.UseTextureLod:0]]`

**Comment by WakuWakuPadoru** [comment]
> [Engine.zip](https://github.com/user-attachments/files/18813421/Engine.zip)
> 
> [LocalStorage.zip](https://github.com/user-attachments/files/18813424/LocalStorage.zip)

Can you try the unlocker again? Cause I see that the LocalStorage doesn't have RT enabled, so I'm not sure if you sent the wrong file or didn't run the unlocker yet.

**Comment by WakuWakuPadoru** [comment]
> I am digging the the client log and it is the log also says it is enabled
> 
> `[2025.02.15-19.39.36:227][ 0][GameThread]LogRendererCore: Ray tracing is enabled (dynamic) for the game. Reason: r.RayTracing=1 and r.RayTracing.EnableOnDemand=1.`
> 
> But it certainly isn't because I still have the same FPS as it was off and I do not see any RT reflection standing in front of a lake Not sure if these lines of log are expected: `[2025.02.15-19.39.35:809][ 0][GameThread]LogConfig: Setting CVar [[r.RayTracing:1]] [2025.02.15-19.39.35:809][ 0][GameThread]LogConfig: Setting CVar [[r.RayTracing.Enable:0]] [2025.02.15-19.39.35:809][ 0][GameThread]LogConfig: Setting CVar [[r.RayTracing.UseTextureLod:0]]`

Can I check what version of the unlocker did you use?

**Comment by xxqt** [comment]
I am using the newest version v0.83. 

By dx12 mode do mean "launch with directx11" option?

[LocalStorage.zip](https://github.com/user-attachments/files/18813538/LocalStorage.zip)

[Engine.zip](https://github.com/user-attachments/files/18813540/Engine.zip)

These are the files after I just after I ran the unlocker

**Comment by WakuWakuPadoru** [comment]
> I am using the newest version v0.83.
> 
> By dx12 mode do mean "launch with directx11" option?
> 
> [LocalStorage.zip](https://github.com/user-attachments/files/18813538/LocalStorage.zip)
> 
> [Engine.zip](https://github.com/user-attachments/files/18813540/Engine.zip)
> 
> These are the files after I just after I ran the unlocker

Yeah but don't check it.

**Comment by WakuWakuPadoru** [comment]
> I am using the newest version v0.83.
> 
> By dx12 mode do mean "launch with directx11" option?
> 
> [LocalStorage.zip](https://github.com/user-attachments/files/18813538/LocalStorage.zip)
> 
> [Engine.zip](https://github.com/user-attachments/files/18813540/Engine.zip)
> 
> These are the files after I just after I ran the unlocker

Can you run the game after using the unlocker? once you get into the game pass the character screen, restart the game one more time.
If it still doesn't work, send the files again. I would like to see if the game is somehow modifying the settings. 

+ Make sure DX11 is UNCHECKED on the launcher. DON'T SELECT IT.

**Comment by xxqt** [comment]
I've always ran the game with dx11 unchecked

**Comment by WakuWakuPadoru** [comment]
> I've always ran the game with dx11 unchecked

Can you try what I suggested? The files are modified correctly based on what you sent me so far but whether the game further modified it beyond that is something that I'm not too sure of. 

So just restart twice after the unlocker is applied.

**Comment by xxqt** [comment]
[Engine.zip](https://github.com/user-attachments/files/18813571/Engine.zip)

[LocalStorage.zip](https://github.com/user-attachments/files/18813572/LocalStorage.zip)

I've tried the method you described. unfortunately the same result

**Comment by WakuWakuPadoru** [comment]
> [Engine.zip](https://github.com/user-attachments/files/18813571/Engine.zip)
> 
> [LocalStorage.zip](https://github.com/user-attachments/files/18813572/LocalStorage.zip)
> 
> I've tried the method you described. unfortunately the same result

To be honest, probably better to wait for the official implementation :(

The files look correct and everything seems like it should fit properly. Even the logs indicate that RayTracing is enabled so at this point, it might just be a bug with the game. The game doesn't allow you to force a shader recompile as well, so options are quite limited.

So far, you're the only user that I can't quite figure out

**Comment by WakuWakuPadoru** [comment]
> I am digging the the client log and it is the log also says it is enabled
> 
> `[2025.02.15-19.39.36:227][ 0][GameThread]LogRendererCore: Ray tracing is enabled (dynamic) for the game. Reason: r.RayTracing=1 and r.RayTracing.EnableOnDemand=1.`
> 
> But it certainly isn't because I still have the same FPS as it was off and I do not see any RT reflection standing in front of a lake Not sure if these lines of log are expected: `[2025.02.15-19.39.35:809][ 0][GameThread]LogConfig: Setting CVar [[r.RayTracing:1]] [2025.02.15-19.39.35:809][ 0][GameThread]LogConfig: Setting CVar [[r.RayTracing.Enable:0]] [2025.02.15-19.39.35:809][ 0][GameThread]LogConfig: Setting CVar [[r.RayTracing.UseTextureLod:0]]`

Well, standard questions. Is Xess disabled in your DB file? (Either unlocker or manually). DX12 mode, yes? Drivers updated, Windows 11? If you have restarted the game a few times AND the config files indicate RT is on, it might just be a bug with the game. By right, it's supposed to do a shader recompile when you enable RT...but WuWa doesn't let the user force a recompile. So somewhere along the chain, something broke.

**Comment by xxqt** [comment]
> > [Engine.zip](https://github.com/user-attachments/files/18813571/Engine.zip)
> > [LocalStorage.zip](https://github.com/user-attachments/files/18813572/LocalStorage.zip)
> > I've tried the method you described. unfortunately the same result
> 
> To be honest, probably better to wait for the official implementation :(
> 
> The files look correct and everything seems like it should fit properly. Even the logs indicate that RayTracing is enabled so at this point, it might just be a bug with the game. The game doesn't allow you to force a shader recompile as well, so options are quite limited.
> 
> So far, you're the only user that I can't quite figure out

Yeah I thought so. thanks for you time

**Comment by zeris55** [comment]
litmuss55 from reddit.

[Engine.zip](https://github.com/user-attachments/files/18817124/Engine.zip)

[LocalStorage.zip](https://github.com/user-attachments/files/18817127/LocalStorage.zip)

**Comment by zeris55** [comment]
after reinstalling, the second boot triggered the compiling shaders, and im not sure if the ray tracing is on or off by now.
![Image](https://github.com/user-attachments/assets/54f53589-bf6a-4959-9f45-4db9dc7391f3)

**Comment by WakuWakuPadoru** [comment]
> after reinstalling, the second boot triggered the compiling shaders, and im not sure if the ray tracing is on or off by now.
> ![Image](https://github.com/user-attachments/assets/54f53589-bf6a-4959-9f45-4db9dc7391f3)

It should be if the shaders compiled. Use a body of water instead and move your mouse downwards. If the reflections don't dissappear, RT is on.

**Comment by zeris55** [comment]
game's graphics too good can't tell the difference, i assume it is on?

![Image](https://github.com/user-attachments/assets/db2ded6d-9501-4d9d-b9c9-6da2ebb6747b)

**Comment by zeris55** [comment]
i have confirmed, yes it is on now thank goodness, the app works

**Comment by WakuWakuPadoru** [comment]
> i have confirmed, yes it is on now thank goodness, the app works

Great! Enjoy!

**Comment by a4840639** [comment]
I figure out: it seems you must launch the game using the launcher after enabling RT to trigger the shader compilation
I always launch the game directly without the launcher (because sometimes I just use my mouse on my laptop and I just want to use keyboard to launch game and play with a controller). Once I launch using the launcher, I got the shader compilation for RT and I can see the FPS dropped a lot

**Comment by WakuWakuPadoru** [comment]
> I figure out: it seems you must launch the game using the launcher after enabling RT to trigger the shader compilation I always launch the game directly without the launcher (because sometimes I just use my mouse on my laptop and I just want to use keyboard to launch game and play with a controller). Once I launch using the launcher, I got the shader compilation for RT and I can see the FPS dropped a lot

Thanks. I will do a reminder in the unlocker in the next update along with other improvements. 

@xxqt Perhaps this would work for you too?

**Comment by WakuWakuPadoru** [comment]
> Actually it is not about the shader compilation/initialization, it seems the RT functionality just does not work unless you launch the game from the launcher

Noted. It's likely that the launcher has additional launch parameters or adds additional cvars to make it work. That's probably not something that I can change unfortunately.

**Comment by paulandrey47** [comment]
I have a strange issue where it always launched with DX11, even after unchecking the "Use DX11" in the launcher.
Here's some excerpt from the client log:
[GameThread]LogInit: OS: Windows 10 (Release 2009) (), CPU: AMD Ryzen Z1 Extreme                           , GPU: AMD Radeon 740M Graphics
[GameThread]LogInit: Compiled (64-bit): Feb 24 2025 16:10:21
[GameThread]LogInit: Compiled with Visual C++: 19.29.30151.00
[GameThread]LogInit: Build Configuration: Shipping
[GameThread]LogInit: Branch Name: ++UE4+Release-4.26
[GameThread]LogInit: Command Line:  -dx11 -DisableModule=dlss
[GameThread]LogInit: Base Directory: C:/Wuthering Waves/Wuthering Waves Game/Client/Binaries/Win64/
[GameThread]LogInit: Allocator: binned2
[GameThread]LogInit: Installed Engine Build: 1

The IGPU in the Ryzen Z1 Extreme is capable of ray tracing (I'm sure it will be pretty laggy but... I'm curious)

What can possibly made it so? any help is appreciated!

**Comment by fudgeyrx** [comment]
Hi. The db file does not seem to generate the 3 raytracing keys (to be edited to 3.1.1) for me. I've reinstalled multiple times, deleted both engine.ini and the dB file for re-generation to no avail. This makes raytracing impossible due to the missing keys.

Is there something I'm missing out on?
Currently running 5800x3d and 7900xtx.
Thank you!
